### PR TITLE
Configure Commitlint

### PR DESCRIPTION
**Pull request by bulldog98**
This implements the action for #197

### CODE REVIEW

**Comment by raoulvdberge** [comment]
Thanks, I've set the commitlint action to be required in order to merge PRs.

Also, congrats on being the first contributor (apart from myself) on this repository!

**Comment by raoulvdberge** [comment]
Hm, I have no idea why Sonarqube is failing...

**Comment by raoulvdberge** [comment]
Weird, on my other PR (https://github.com/refinedmods/refinedstorage2/pull/250) Sonar step has succeeded. I'm assuming it's something permission related...

**Comment by bulldog98** [comment]
Yeah has to be something wit permissions, how do you prefer updates for PRs, rebase or merge?

**Comment by bulldog98** [comment]
Maybe the problem is that your PR was a branch in refinedmods/refinedstorage2, while mine is in my personal fork? I'm not sure how that would be fixed, but it is something that needs addressing, if you want contributions from externals

**Comment by bulldog98** [comment]
Regarding Sonarqube, I did a bit of research and it looks like it's not possible to run sonarqube on external PRs https://portal.productboard.com/sonarsource/1-sonarcloud/c/50-sonarcloud-analyzes-external-pull-request

After even more research it looks like using pull_request_target instead of pull_request does what we need https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/#improvements-for-public-repository-forks

**Comment by raoulvdberge** [comment]
I'm not sure whether pull_request_target will work:

> However, instead of running against the workflow and code from the merge commit, the event runs against the workflow and code from the base of the pull request.

Wouldn't this only provide the latest code from develop to Sonarqube, instead of the changes on the PR?

**Comment by bulldog98** [comment]
@raoulvdberge I understood it as the workflow is taken from develop

**Comment by raoulvdberge** [comment]
I've just disabled the Sonar checks on forked PRs for now. We can look into it further later, but I don't really have time to investigate deeper right now. :)

**Pull request merged**
